#- id: doi:10.1371/journal.pcbi.1007128
#  type: paper
#  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#  date: 2020-12-4
#  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#  buttons:
#    - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      text: Manuscript Source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/
#  tags:
#    - open science
#    - collaboration
#  repo: greenelab/meta-review

#- id: doi:10.1016/j.csbj.2020.05.017
#  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

#- id: doi:10.7554/eLife.32822
#  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: doi:10.3390/biotech13010003
  image: https://www.mdpi.com/biotech/biotech-13-00003/article_deploy/html/images/biotech-13-00003-g001.png
  
- id: doi:10.1145/3664923
  image: ../images/publications/fixed_point.png

- id: doi:10.1142/S0219633620400027
  image: ../images/publications/S0219633620400027.jpg

- id: doi:10.3389/fmolb.2021.784303
  image: ../images/publications/784303.jpg

- id: doi:10.1101/2021.06.30.450547
  image: ../images/publications/784303.jpg

- id: doi:10.1142/S0219633620410035
  image: ../images/publications/S0219633620410035.jpeg

- id:  doi:10.3389/fmolb.2021.718587
  image: ../images/publications/718587.jpg

- id: doi:10.3390/ijms23042035
  image: ../images/publications/ijms23042035.jpg

- id: doi:10.1096/FASEBJ.2022.36.S1.0R568
  image: ../images/publications/0R568.png

- id: doi:10.3934/MBE.2021120
  image: ../images/publications/2021120.jpg

- id: doi:10.1016/j.csbj.2021.01.020
  image: ../images/publications/01020.jpg

- id: doi:10.3390/ijms241511928
  image: ../images/publications/ijms241511928.png

- id: doi:10.3390/life13040981
  image: ../images/publications/life13040981.png

- id: doi:10.1109/MCSE.2020.3015511
  image: ../images/publications/3015511.gif

- id: doi:10.3389/fmolb.2020.591873
  image: ../images/publications/591873.jpg

- id: doi:10.3389/fmolb.2020.627087
  image: ../images/publications/627087.jpg

- id: doi:10.1142/S2737416520420089 
  image: ../images/publications/S2737416520420089.jpg

- id: doi:10.3390/pathogens11020238 
  image: ../images/publications/11020238.png

- id: doi:10.1515/cmb-2019-0005
  image: ../images/publications/cmb-2019-0005.png